# Generated by Django 5.1.3 on 2024-12-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG'), ('CNH', 'CNH'), ('PASSAPORTE', 'Passaporte'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('CONTRATO_SOCIAL', 'Contrato Social')], max_length=50)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('arrematante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='user_management.arrematante')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='user_management.vendedor')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
