# Generated by Django 5.1.3 on 2024-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_admin_arrematante_vendedor_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrematante',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='cpf_cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='logradouro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='telefone_celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='arrematante',
            name='tipo_cadastro',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo_cadastro',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
    ]
