# Generated by Django 5.1.3 on 2024-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_arrematante_telefone_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrematante',
            name='cpf_cnpj',
            field=models.CharField(max_length=30),
        ),
    ]
