# Generated by Django 5.1.3 on 2024-12-18 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Lance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Lance')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Lance Válido')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction_management.ruralitem', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status do Pagamento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('other_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='auction_management.othergoods', verbose_name='Outro Bem')),
                ('real_estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='auction_management.realestate', verbose_name='Imóvel')),
                ('rural_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='auction_management.ruralitem', verbose_name='Item Rural')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Arrematante')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='auction_management.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date'],
            },
        ),
    ]
