# Generated by Django 5.1.3 on 2024-12-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Item')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Lance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Lance')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Lance Válido')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='contenttypes.contenttype', verbose_name='Tipo de Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Arrematante')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Item')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status do Pagamento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contenttypes.contenttype', verbose_name='Tipo de Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Arrematante')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date'],
            },
        ),
    ]
