# Generated by Django 5.1.3 on 2024-12-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0004_remove_othergoods_bids_remove_realestate_bids_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='other_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lances_othergoods', to='auction_management.othergoods'),
        ),
        migrations.AddField(
            model_name='bid',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lances_realestate', to='auction_management.realestate'),
        ),
        migrations.AddField(
            model_name='bid',
            name='rural_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lances_ruralitem', to='auction_management.ruralitem'),
        ),
        migrations.AddField(
            model_name='bid',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lances_vehicle', to='auction_management.vehicle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='other_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_othergoods', to='auction_management.othergoods'),
        ),
        migrations.AddField(
            model_name='payment',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_realestate', to='auction_management.realestate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rural_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_ruralitem', to='auction_management.ruralitem'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_vehicle', to='auction_management.vehicle'),
        ),
    ]
