# Generated by Django 5.1.3 on 2024-12-05 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('codigo_leilao', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código do Leilão')),
                ('descricao', models.TextField(verbose_name='Descrição do Leilão')),
                ('comitente', models.CharField(max_length=255, verbose_name='Comitente')),
                ('complemento', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Leilão')),
                ('duration_hours', models.PositiveIntegerField(default=2, verbose_name='Duração do Leilão (em horas)')),
                ('quantidade_lotes', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Lotes')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Lance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Lance')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Lance Válido')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Itens',
            },
        ),
        migrations.CreateModel(
            name='OtherGoods',
            fields=[
                ('nome', models.CharField(default='Item', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Avaliado')),
                ('codigo_item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código do Item')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('estado_item', models.CharField(max_length=50, verbose_name='Estado do Item')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('nome', models.CharField(default='Item', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Avaliado')),
                ('codigo_item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código do Item')),
                ('quartos', models.IntegerField(verbose_name='Quartos')),
                ('metragem', models.FloatField(verbose_name='Metragem')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('estado_imovel', models.CharField(max_length=50, verbose_name='Estado do Imóvel')),
            ],
        ),
        migrations.CreateModel(
            name='RuralItem',
            fields=[
                ('nome', models.CharField(default='Item', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Avaliado')),
                ('codigo_item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código do Item')),
                ('origem', models.CharField(default='Rural', max_length=50, verbose_name='Origem')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('nome', models.CharField(default='Item', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Avaliado')),
                ('codigo_item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código do Item')),
                ('versao', models.CharField(max_length=100, verbose_name='Versão')),
                ('fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('categoria_veiculo', models.CharField(max_length=50, verbose_name='Categoria do Veículo')),
                ('fipe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor FIPE')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('tipo_monta', models.CharField(max_length=50, verbose_name='Tipo de Monta')),
                ('tipo_chassi', models.CharField(max_length=50, verbose_name='Tipo de Chassi')),
                ('blindado', models.BooleanField(default=False, verbose_name='Blindado')),
                ('condicao', models.CharField(max_length=50, verbose_name='Condição')),
                ('condicao_funcionamento', models.CharField(max_length=50, verbose_name='Condição de Funcionamento')),
                ('numero_chassi', models.CharField(max_length=50, verbose_name='Número do Chassi')),
                ('chave', models.BooleanField(default=False, verbose_name='Possui Chave')),
                ('final_placa', models.CharField(max_length=1, verbose_name='Final da Placa')),
                ('combustivel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('patio', models.CharField(max_length=100, verbose_name='Pátio')),
            ],
        ),
    ]
