# Generated by Django 5.1.3 on 2024-11-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=50, verbose_name='Código do Item')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('codigo_leilao', models.CharField(max_length=50, verbose_name='Código do Leilão')),
                ('descricao', models.TextField(verbose_name='Descrição do Leilão')),
                ('comitente', models.CharField(max_length=255, verbose_name='Comitente')),
                ('complemento', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.auctioncategory', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OtherGoods',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction_management.baseitem')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Avaliado')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('estado_item', models.CharField(max_length=50, verbose_name='Estado do Item')),
            ],
            bases=('auction_management.baseitem',),
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction_management.baseitem')),
                ('quartos', models.IntegerField(verbose_name='Quartos')),
                ('metragem', models.FloatField(verbose_name='Metragem')),
                ('valor_avaliado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Avaliado')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('estado_imovel', models.CharField(max_length=50, verbose_name='Estado do Imóvel')),
            ],
            bases=('auction_management.baseitem',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction_management.baseitem')),
                ('versao', models.CharField(max_length=100, verbose_name='Versão')),
                ('fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('categoria_veiculo', models.CharField(max_length=50, verbose_name='Categoria do Veículo')),
                ('fipe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor FIPE')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('tipo_monta', models.CharField(max_length=50, verbose_name='Tipo de Monta')),
                ('tipo_chassi', models.CharField(max_length=50, verbose_name='Tipo de Chassi')),
                ('blindado', models.BooleanField(default=False, verbose_name='Blindado')),
                ('condicao', models.CharField(max_length=50, verbose_name='Condição')),
                ('condicao_funcionamento', models.CharField(max_length=50, verbose_name='Condição de Funcionamento')),
                ('numero_chassi', models.CharField(max_length=50, verbose_name='Número do Chassi')),
                ('chave', models.BooleanField(default=False, verbose_name='Possui Chave')),
                ('final_placa', models.CharField(max_length=1, verbose_name='Final da Placa')),
                ('combustivel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('patio', models.CharField(max_length=100, verbose_name='Pátio')),
            ],
            bases=('auction_management.baseitem',),
        ),
        migrations.CreateModel(
            name='RuralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='Rural', max_length=50, verbose_name='Origem')),
                ('tipo_item', models.CharField(choices=[('Imóvel', 'Imóvel'), ('Veículo', 'Veículo'), ('Outros Bens', 'Outros Bens')], max_length=50, verbose_name='Tipo do Item')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_management.baseitem', verbose_name='Item Associado')),
            ],
        ),
    ]
