# Generated by Django 5.1.3 on 2024-12-01 00:40

import auction_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(default=auction_management.models.default_auction_time, verbose_name='Data e Hora do Leilão'),
        ),
    ]
