# Generated by Django 5.1.3 on 2024-12-05 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction_management', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.auctioncategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_goods', to='auction_management.auction', verbose_name='Leilão'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_management.itemtype', verbose_name='Tipo do Item'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to='auction_management.auction', verbose_name='Leilão'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_management.itemtype', verbose_name='Tipo do Item'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rural_items', to='auction_management.auction', verbose_name='Leilão'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_management.itemtype', verbose_name='Tipo do Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction_management.ruralitem', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='auction_management.auction', verbose_name='Leilão'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_management.itemtype', verbose_name='Tipo do Item'),
        ),
    ]
