# Generated by Django 5.1.3 on 2024-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='itens/', verbose_name='Imagem do Item')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Imagem')),
            ],
            options={
                'verbose_name': 'Imagem do Item',
                'verbose_name_plural': 'Imagens dos Itens',
            },
        ),
        migrations.AlterModelOptions(
            name='othergoods',
            options={'verbose_name': 'Outro Bem', 'verbose_name_plural': 'Outros Bens'},
        ),
        migrations.RemoveField(
            model_name='othergoods',
            name='estado_item',
        ),
        migrations.RemoveField(
            model_name='othergoods',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='auction',
            name='documento_editais',
            field=models.FileField(blank=True, null=True, upload_to='editais/', verbose_name='Documento Edital (PDF)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='imagem',
            field=models.ImageField(default='default/default_image.jpg', upload_to='leiloes/'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='status_lote',
            field=models.CharField(choices=[('aceitando_lances', 'Aceitando lances'), ('arrematado', 'Arrematado'), ('pendente_de_pagamento', 'Pendente de pagamento')], default='aceitando_lances', max_length=50, verbose_name='Status do Lote'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=50, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='valor_arrematado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Arrematado'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='status_lote',
            field=models.CharField(choices=[('aceitando_lances', 'Aceitando lances'), ('arrematado', 'Arrematado'), ('pendente_de_pagamento', 'Pendente de pagamento')], default='aceitando_lances', max_length=50, verbose_name='Status do Lote'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=50, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='valor_arrematado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Arrematado'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='status_lote',
            field=models.CharField(choices=[('aceitando_lances', 'Aceitando lances'), ('arrematado', 'Arrematado'), ('pendente_de_pagamento', 'Pendente de pagamento')], default='aceitando_lances', max_length=50, verbose_name='Status do Lote'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=50, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='valor_arrematado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Arrematado'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_lote',
            field=models.CharField(choices=[('aceitando_lances', 'Aceitando lances'), ('arrematado', 'Arrematado'), ('pendente_de_pagamento', 'Pendente de pagamento')], default='aceitando_lances', max_length=50, verbose_name='Status do Lote'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=50, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='valor_arrematado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Arrematado'),
        ),
        migrations.AddField(
            model_name='othergoods',
            name='imagens',
            field=models.ManyToManyField(related_name='other_goods', to='auction_management.itemimage', verbose_name='Imagens do Item'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='imagens',
            field=models.ManyToManyField(related_name='real_estates', to='auction_management.itemimage', verbose_name='Imagens do Imóvel'),
        ),
        migrations.AddField(
            model_name='ruralitem',
            name='imagens',
            field=models.ManyToManyField(related_name='rural_items', to='auction_management.itemimage', verbose_name='Imagens do Item Rural'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='imagens',
            field=models.ManyToManyField(related_name='vehicles', to='auction_management.itemimage', verbose_name='Imagens do Veículo'),
        ),
    ]
