# Generated by Django 5.1.3 on 2024-12-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0002_auction_active_auction_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem',
            name='codigo_item',
        ),
        migrations.RemoveField(
            model_name='othergoods',
            name='valor_avaliado',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='valor_avaliado',
        ),
        migrations.AddField(
            model_name='baseitem',
            name='nome',
            field=models.CharField(default='Item', max_length=255, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='valor_avaliado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Avaliado'),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Lance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Lance')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Lance Válido')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction_management.baseitem', verbose_name='Item do Leilão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['-timestamp'],
            },
        ),
    ]
