# Generated by Django 5.1.3 on 2024-12-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othergoods',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='ruralitem',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='imagens',
        ),
    ]
