# Generated by Django 5.1.3 on 2024-12-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='other_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_othergoods', to='auction_management.othergoods'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_realestate', to='auction_management.realestate'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='rural_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_ruralitem', to='auction_management.ruralitem'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_vehicle', to='auction_management.vehicle'),
        ),
    ]
