# Generated by Django 5.1.3 on 2024-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0003_remove_baseitem_codigo_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='codigo_item',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='Código do Item'),
        ),
    ]
