# Generated by Django 5.1.3 on 2024-12-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0003_remove_othergoods_imagens_remove_realestate_imagens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othergoods',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='ruralitem',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='bids',
        ),
    ]
