# Generated by Django 5.1.3 on 2024-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0003_itemimage_alter_othergoods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imagem',
            field=models.ImageField(default='media/default/default_image.jpg', upload_to='media/leiloes/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='imagem',
            field=models.ImageField(upload_to='media/itens/', verbose_name='Imagem do Item'),
        ),
    ]
