# Generated by Django 5.1.3 on 2024-12-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0004_remove_othergoods_bids_remove_realestate_bids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('programado', 'Programado'), ('ao_vivo', 'Ao Vivo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=10, verbose_name='Status do Leilão'),
        ),
    ]
