# Generated by Django 5.1.3 on 2024-12-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0004_baseitem_codigo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Duração do Leilão (em horas)'),
        ),
    ]
