# Generated by Django 5.1.3 on 2024-12-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0004_alter_auction_imagem_alter_itemimage_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imagem',
            field=models.ImageField(default='default/default_image.jpg', upload_to='leiloes/'),
        ),
    ]
