# Generated by Django 5.1.3 on 2024-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0005_alter_auction_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='nome',
            field=models.CharField(choices=[('Veículo', 'Veículo'), ('Imóvel', 'Imóvel'), ('Outros', 'Outros')], max_length=100, unique=True, verbose_name='Nome do Tipo de Item'),
        ),
    ]
