# Generated by Django 5.1.3 on 2024-12-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0005_remove_auction_active_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ao_vivo_iniciado',
            field=models.BooleanField(default=False, verbose_name='Leilão Ao Vivo Iniciado'),
        ),
    ]
