# Generated by Django 5.1.3 on 2024-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0006_remove_itemtype_descricao_alter_itemtype_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imagem',
            field=models.ImageField(default='default/default_image.jpg', upload_to='vehicles/'),
        ),
    ]
