# Generated by Django 5.1.3 on 2024-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0007_vehicle_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='real_estates/'),
        ),
    ]
