# Generated by Django 5.1.3 on 2024-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Imóveis', 'Imóveis'), ('Veículos', 'Veículos'), ('Rural', 'Rural'), ('Outros Bens', 'Outros Bens')], max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Leilão',
                'verbose_name_plural': 'Categorias de Leilão',
            },
        ),
    ]
