# Generated by Django 5.1.3 on 2024-12-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_management', '0003_remove_baseitem_codigo_item_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncategory',
            name='featured_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_category', to='auction_management.baseitem'),
        ),
    ]
