# Generated by Django 5.1.3 on 2024-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auctioncategory_featured_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncategory',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
